### ISSUE TITLE
plotrecipes dep

### ISSUE THREAD

**Issue by mkborregaard** [baggepinnen/BasisFunctionExpansions.jl#11]
Hi,
this package depends on PlotRecipes, but you don't seem to be using it. I'm guessing it's a mistake and the REQUIRE file should hold `RecipesBase` instead?
BTW very pretty graphs. I *believe* that the color bar issue with the Plotly surface should be solved on current Plots.

**Comment by baggepinnen** [comment]
Thanks, you're right! I thought I changed it, but turns out I only updated PROJECT.TOML, not REQUIRE 😌
