### ISSUE TITLE
Is there an option to have the input and output be for different dimensions?

### ISSUE THREAD

**Issue by michaelschwob** [baggepinnen/BasisFunctionExpansions.jl#22]
For example, consider the problem y=Mx, where M is mxn dimension and a set of basis functions. Is there a way that we can estimate the basis functions in M here?

**Comment by baggepinnen** [comment]
Like this? https://baggepinnen.github.io/BasisFunctionExpansions.jl/latest/#Multiple-dimensions-1

**Comment by michaelschwob** [comment]
Not exactly. In that example, y is 1000x1 and v is 1000x2, so they both have the same number of rows. I'm wondering if this package can accomodate the case where y is 1000x1 and, say, v is 500x2, where y and v have a different number of rows.

**Comment by baggepinnen** [comment]
I'm not sure what that would represent. This package primarily aims at modeling functions $y = f(x)$ from $R^n \rightarrow R$, The first dimension in those arrays are just the number of input-output pairs $(x, y)$, it does not make sense to have them not be equal.

**Comment by michaelschwob** [comment]
That is what I was thinking. The package works great for that objective. I was just wondering if I could use it for a case like this.
